backend:
  name: git-gateway
  branch: main
media_folder: static/img/uploads
public_folder: /public/img/uploads
collections:
  - name: coworker
    label: Medarbetare
    folder: content/medarbetare
    create: true
    fields:
      - label: Namn
        name: name
        widget: string
      - label: E-post
        name: email
        widget: string
      - label: Telefon
        name: phone
        widget: string
      - label: Beskrivning
        name: description
        widget: markdown
      - label: Profilbild
        name: image
        widget: image
      - label: Jobbtitel
        name: jobTitle
        widget: string
      - label: Biografi
        name: bio
        widget: markdown
